#!/usr/bin/env python3
"""Regenerate the source-code manifest inside docs/knowledge_base.md.

The manifest was hand-maintained and went 7 commits stale — it described the code as of
Phase 4 while M5 and all of Phase 9 were already committed, so anyone reading it concluded
the memory hub did not exist. A doc that mirrors the tree has to be derived from the tree;
maintaining it by hand just schedules the next drift.

    python scripts/gen_manifest.py            # rewrite the section in place
    python scripts/gen_manifest.py --check    # exit 1 if stale (for CI)

ponytail: whole-file embedding, same as the hand-written version it replaces. If the KB gets
unwieldy, emit signatures + docstrings instead — the splice logic does not change.
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KB = ROOT / "docs" / "knowledge_base.md"

BEGIN = "<!-- MANIFEST:BEGIN — generated by scripts/gen_manifest.py, do not edit by hand -->"
END = "<!-- MANIFEST:END -->"

# Ordered so the manifest reads architecturally rather than alphabetically: entrypoint,
# config, then each layer inward, then tests, then packaging.
GLOBS = [
    "app/main.py",
    "app/core/*.py",
    "app/agents/*.py",
    "app/graph/*.py",
    "app/memory/*.py",
    "app/db/*.py",
    "app/services/*.py",
    "tests/**/*.py",
    "Dockerfile",
    "docker-compose.yml",
    "requirements.txt",
    "README.md",
]

_LANG = {".py": "python", ".yml": "yaml", ".yaml": "yaml", ".md": "", ".txt": ""}


def _files():
    """Resolve GLOBS to real paths, de-duplicated, order preserved."""
    seen, out = set(), []
    for pattern in GLOBS:
        matches = sorted(ROOT.glob(pattern)) if any(c in pattern for c in "*?") else [ROOT / pattern]
        for path in matches:
            if not path.is_file() or "__pycache__" in path.parts:
                continue
            rel = path.relative_to(ROOT).as_posix()
            if rel not in seen:
                seen.add(rel)
                out.append(path)
    return out


def render() -> str:
    chunks = [
        BEGIN,
        "",
        f"> **Generated.** {len(_files())} files, regenerated by `scripts/gen_manifest.py`.",
        "> Run it after any commit that adds or removes a module — or let CI fail on",
        "> `--check`. Do not hand-edit between the markers; the next run overwrites it.",
        "",
    ]
    for path in _files():
        rel = path.relative_to(ROOT).as_posix()
        body = path.read_text(encoding="utf-8", errors="replace").rstrip("\n")
        fence = "````" if "```" in body else "```"   # README embeds fences of its own
        chunks.append(f"### File: `{rel}`")
        chunks.append(f"{fence}{_LANG.get(path.suffix, '')}")
        chunks.append(body)
        chunks.append(fence)
        chunks.append("")
    chunks.append(END)
    return "\n".join(chunks)


def splice(text: str, manifest: str) -> str:
    """Replace the manifest block. Markers if present, else the original heading span."""
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        return head + manifest + rest.split(END, 1)[1]

    # First run: the section is bounded by its own heading and the next numbered one.
    start = text.index("## 📁 3. Complete Source Code Manifest")
    start = text.index("\n", start) + 1
    stop = text.index("## 🔍 4. CompTrack Legacy Architecture")
    return text[:start] + "\n" + manifest + "\n\n---\n\n" + text[stop:]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the manifest is stale")
    args = ap.parse_args()

    current = KB.read_text(encoding="utf-8")
    updated = splice(current, render())

    if args.check:
        if current == updated:
            print("manifest up to date")
            return 0
        print("STALE: docs/knowledge_base.md manifest does not match the tree", file=sys.stderr)
        print("       run: python scripts/gen_manifest.py", file=sys.stderr)
        return 1

    KB.write_text(updated, encoding="utf-8")
    print(f"[+] manifest regenerated: {len(_files())} files, {len(updated.splitlines())} lines total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
